# Generated by Django 2.2.1 on 2019-07-27 09:21

from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# fb_post.migrations.0004_auto_20190726_1657

def combine_names(apps, schema_editor):
    Person = apps.get_model('fb_post', 'Person')
    for person in Person.objects.all():
        person.name = person.firstname + " " + person.lastname
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0001_squashed_0003_auto_20190726_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
            ],
        ),
        migrations.RunPython(
            combine_names
        ),
    ]
