# Generated by Django 2.2.1 on 2019-07-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0007_auto_20190726_1813'),
        ('fb_post', '0002_person_squashed_0004_auto_20190726_1657'),
    ]

    operations = [
    ]
