# Generated by Django 2.2.1 on 2019-07-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0009_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='username',
        ),
    ]
