# Generated by Django 2.2.1 on 2019-07-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0010_changed_person_name_to_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='username',
            new_name='username_updated',
        ),
    ]
