# Generated by Django 2.2.1 on 2019-07-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0011_auto_20190727_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='username_updated',
            new_name='username_new_branch',
        ),
    ]
