# Generated by Django 2.2.1 on 2019-07-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0012_auto_20190727_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='username',
            new_name='username_updated',
        ),
    ]
